// Mock data for IQC Academy frontend

export const mockUser = {
  id: 'USR-2025-001',
  name: 'আব্দুর রহমান',
  email: 'rahman@example.com',
  mobile: '01712345678',
  whatsapp: '01712345678',
  facebook: 'https://facebook.com/rahman',
  institution: 'ঢাকা বিশ্ববিদ্যালয়',
  division: 'ঢাকা',
  district: 'ঢাকা',
  upazila: 'সাভার',
  dob: '2000-05-15',
  sscYear: '2018',
  sscBoard: 'ঢাকা',
  sscGpa: '5.00',
  avatar: null,
  joinedDate: '2025-01-15',
  status: 'active',
  coursesCompleted: 3,
  coursesEnrolled: 5,
  totalCourses: 12,
  overallProgress: 58,
  currentStreak: 7,
  totalPoints: 1240,
};

export const mockNotices = [
  {
    id: 1,
    title: 'রমজান বিশেষ কোর্স শুরু হচ্ছে!',
    body: 'আগামী সপ্তাহ থেকে রমজান মাসের বিশেষ কোর্স শুরু হবে। সকলকে রেজিস্ট্রেশন করার অনুরোধ করা হচ্ছে।',
    date: '২০২৫-০১-১০',
    link: '/courses',
    linkText: 'কোর্স দেখুন',
    important: true,
  },
  {
    id: 2,
    title: 'নতুন কন্টেন্ট আপলোড হয়েছে',
    body: 'তাফসিরুল কুরআন সিরিজের নতুন পর্ব আপলোড হয়েছে। পড়ুন এবং কুইজ দিন।',
    date: '২০২৫-০১-০৮',
    link: '/content',
    linkText: 'পড়ুন',
    important: false,
  },
  {
    id: 3,
    title: 'সাপ্তাহিক অনলাইন ক্লাস',
    body: 'প্রতি শুক্রবার রাত ৯টায় অনলাইন ক্লাস অনুষ্ঠিত হবে। Zoom লিংকের জন্য যোগাযোগ করুন।',
    date: '২০২৫-০১-০৬',
    link: null,
    linkText: null,
    important: false,
  },
];

export const mockBannerSlides = [
  {
    id: 1,
    title: 'ইলম অর্জন করুন, জান্নাতের পথ খুঁজুন',
    subtitle: 'IQC Academy-তে স্বাগতম',
    bgColor: 'linear-gradient(135deg, hsl(145,63%,22%) 0%, hsl(145,50%,30%) 100%)',
    icon: '📖',
  },
  {
    id: 2,
    title: 'প্রতিদিন একটু একটু শিখুন',
    subtitle: 'কোর্স, কুইজ এবং আরও অনেক কিছু',
    bgColor: 'linear-gradient(135deg, hsl(38,80%,40%) 0%, hsl(38,70%,50%) 100%)',
    icon: '🌙',
  },
  {
    id: 3,
    title: 'অনলাইন মাদ্রাসায় ভর্তি হন',
    subtitle: 'আলেমদের তত্ত্বাবধানে কুরআন ও হাদিস শিখুন',
    bgColor: 'linear-gradient(135deg, hsl(210,60%,30%) 0%, hsl(145,45%,25%) 100%)',
    icon: '🕌',
  },
];

export const mockSectionNav = [
  { id: 'content',  label: 'কন্টেন্ট সমূহ',      icon: '📚', href: '/content',  color: 'hsl(145,63%,22%)' },
  { id: 'courses',  label: 'কোর্স',             icon: '🎓', href: '/courses',  color: 'hsl(38,80%,48%)'  },
  { id: 'madrasa',  label: 'অনলাইন মাদ্রাসা',    icon: '🕌', href: '/madrasa',  color: 'hsl(210,60%,40%)' },
  { id: 'paid',     label: 'পেইড কোর্স',         icon: '💎', href: '/courses?type=paid', color: 'hsl(280,50%,40%)' },
  { id: 'projects', label: 'আমাদের প্রজেক্ট',    icon: '🌟', href: '/projects', color: 'hsl(15,70%,45%)'  },
  { id: 'gallery',  label: 'গ্যালারি',            icon: '🖼️', href: '/gallery',  color: 'hsl(175,50%,35%)' },
  { id: 'donate',   label: 'ডোনেট করুন',         icon: '💝', href: '/donate',   color: 'hsl(350,60%,45%)' },
  { id: 'profile',  label: 'আমার প্রোফাইল',      icon: '👤', href: '/profile',  color: 'hsl(220,50%,40%)' },
];

export const mockContents = [
  {
    id: 1,
    title: 'তাফসিরুল কুরআন — সূরা আল-ফাতিহা',
    type: 'text',
    description: 'সূরা আল-ফাতিহার বিস্তারিত তাফসির, অর্থ ও প্রাসঙ্গিক হাদিস সহ।',
    cover: null,
    body: `বিসমিল্লাহির রাহমানির রাহিম\n\nসূরা আল-ফাতিহা কুরআনের প্রথম সূরা। এটি উম্মুল কিতাব (কিতাবের মা) নামেও পরিচিত।\n\nআরবি: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ\nবাংলা: সমস্ত প্রশংসা আল্লাহর, যিনি সমগ্র বিশ্বের প্রতিপালক।\n\nএই সূরা আমাদের শেখায় কিভাবে আল্লাহর কাছে প্রার্থনা করতে হয়।`,
    quizCount: 10,
    quizAttempts: 0,
    maxAttempts: 3,
    isCompleted: false,
    readingTime: '৫ মিনিট',
    publishedDate: '২০২৫-০১-০১',
    tags: ['তাফসির', 'কুরআন', 'সূরা ফাতিহা'],
  },
  {
    id: 2,
    title: 'নামাজের গুরুত্ব ও ফজিলত',
    type: 'video',
    description: 'ইসলামে নামাজের গুরুত্ব নিয়ে বিস্তারিত আলোচনা, দলিলসহ।',
    cover: null,
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    quizCount: 8,
    quizAttempts: 1,
    maxAttempts: 3,
    isCompleted: false,
    readingTime: '১৫ মিনিট',
    publishedDate: '২০২৫-০১-০৩',
    tags: ['নামাজ', 'ফজিলত', 'ইবাদত'],
  },
  {
    id: 3,
    title: 'আকিদা মূলনীতি — পিডিএফ গাইড',
    type: 'pdf',
    description: 'ইসলামি আকিদার মূল বিষয়সমূহ নিয়ে একটি সম্পূর্ণ গাইড।',
    cover: null,
    pdfUrl: '/sample.pdf',
    quizCount: 15,
    quizAttempts: 3,
    maxAttempts: 3,
    isCompleted: true,
    readingTime: '৩০ মিনিট',
    publishedDate: '২০২৪-১২-২০',
    tags: ['আকিদা', 'তাওহীদ', 'ইমান'],
  },
  {
    id: 4,
    title: 'হাদিস শাস্ত্রের পরিচয়',
    type: 'text',
    description: 'হাদিস কি? কিভাবে হাদিস সংকলিত হয়েছে? হাদিসের প্রকারভেদ।',
    cover: null,
    body: 'হাদিস হলো রাসুলুল্লাহ (সা.)-এর বাণী, কাজ ও অনুমোদনের সংকলন।',
    quizCount: 12,
    quizAttempts: 0,
    maxAttempts: 3,
    isCompleted: false,
    readingTime: '১০ মিনিট',
    publishedDate: '২০২৫-০১-০৫',
    tags: ['হাদিস', 'ইসলামি জ্ঞান'],
  },
];

export const mockQuizQuestions = [
  {
    id: 1,
    question: 'সূরা আল-ফাতিহায় মোট কতটি আয়াত আছে?',
    options: ['৫টি', '৬টি', '৭টি', '৮টি'],
    correct: 2,
    explanation: 'সূরা আল-ফাতিহায় ৭টি আয়াত রয়েছে।',
  },
  {
    id: 2,
    question: '"উম্মুল কিতাব" কোন সূরাকে বলা হয়?',
    options: ['সূরা বাকারা', 'সূরা ফাতিহা', 'সূরা ইখলাস', 'সূরা কাওসার'],
    correct: 1,
    explanation: 'সূরা ফাতিহাকে উম্মুল কিতাব (কিতাবের মা) বলা হয়।',
  },
  {
    id: 3,
    question: 'প্রতিদিন ফরজ নামাজে সূরা ফাতিহা কতবার পড়া হয়?',
    options: ['৫ বার', '১৭ বার', '১৩ বার', '১০ বার'],
    correct: 1,
    explanation: '৫ ওয়াক্তে মোট ১৭ রাকাতে সূরা ফাতিহা পড়া হয়।',
  },
  {
    id: 4,
    question: '"রব্বুল আলামিন" মানে কী?',
    options: ['দয়াময়', 'বিশ্বের প্রতিপালক', 'পরম করুণাময়', 'বিচার দিনের মালিক'],
    correct: 1,
    explanation: 'রব্বুল আলামিন মানে — সমগ্র বিশ্বের প্রতিপালক।',
  },
  {
    id: 5,
    question: '"ইয়্যাকা না\'বুদু" আয়াতের অর্থ কী?',
    options: [
      'আমরা তোমার কাছে সাহায্য চাই',
      'আমরা কেবল তোমারই ইবাদত করি',
      'আমাদের সরল পথ দেখাও',
      'তুমিই একমাত্র উপাস্য',
    ],
    correct: 1,
    explanation: '"ইয়্যাকা না\'বুদু" মানে — আমরা কেবল তোমারই ইবাদত করি।',
  },
];

export const mockCourses = [
  {
    id: 1,
    title: 'কুরআন তিলাওয়াত — বেসিক কোর্স',
    description: 'একদম শুরু থেকে মাখরাজ, সিফাত ও তাজবিদ সহ সঠিকভাবে কুরআন তিলাওয়াত শিখুন। সম্পূর্ণ নতুনদের জন্য আদর্শ।',
    type: 'free',
    status: 'enrolled',
    progress: 60,
    completedModules: 3,
    totalModules: 5,
    cover: null,
    coverGradient: 'linear-gradient(135deg, #064E3B 0%, #065F46 100%)',
    instructor: 'মাওলানা আব্দুল করিম',
    instructorTitle: 'শায়খুল হাদিস, জামিয়া ইসলামিয়া ঢাকা',
    duration: '৪ সপ্তাহ',
    level: 'বেসিক',
    enrolledStudents: 1284,
    rating: 4.9,
    ratingCount: 312,
    tags: ['তিলাওয়াত', 'তাজবিদ', 'কুরআন'],
    language: 'বাংলা',
    certificate: true,
    lastUpdated: '২০২৬-০৩-১৫',
    modules: [
      { id: 1, title: 'মাখরাজ ও সিফাত পরিচয়',      isCompleted: true,  isLocked: false, quizPassed: true,  duration: '৪৫ মিনিট' },
      { id: 2, title: 'হরফ চেনা ও সঠিক উচ্চারণ',    isCompleted: true,  isLocked: false, quizPassed: true,  duration: '৫০ মিনিট' },
      { id: 3, title: 'হরকত, তানভিন ও মদ',           isCompleted: true,  isLocked: false, quizPassed: true,  duration: '৬০ মিনিট' },
      { id: 4, title: 'তাজবিদের মূলনীতি',             isCompleted: false, isLocked: false, quizPassed: false, duration: '৫৫ মিনিট' },
      { id: 5, title: 'প্র্যাকটিস ও মূল্যায়ন সেশন',  isCompleted: false, isLocked: true,  quizPassed: false, duration: '৩০ মিনিট' },
    ],
  },
  {
    id: 2,
    title: 'ইসলামের পাঁচ স্তম্ভ — সম্পূর্ণ গাইড',
    description: 'শাহাদাহ, সালাত, যাকাত, সিয়াম ও হজ — ইসলামের মূল পাঁচটি স্তম্ভ সম্পর্কে গভীর এবং প্রাঞ্জল আলোচনা।',
    type: 'free',
    status: 'completed',
    progress: 100,
    completedModules: 6,
    totalModules: 6,
    cover: null,
    coverGradient: 'linear-gradient(135deg, #1E3A5F 0%, #2E5090 100%)',
    instructor: 'মুফতি ইউসুফ আলী',
    instructorTitle: 'মুফতি, ইসলামিক ফাউন্ডেশন বাংলাদেশ',
    duration: '৩ সপ্তাহ',
    level: 'মাঝারি',
    enrolledStudents: 2560,
    rating: 4.8,
    ratingCount: 541,
    tags: ['ফিকহ', 'আকিদা', 'পাঁচ স্তম্ভ'],
    language: 'বাংলা',
    certificate: true,
    lastUpdated: '২০২৬-০২-২০',
    modules: [
      { id: 1, title: 'কালিমা ও শাহাদাহ',              isCompleted: true, isLocked: false, quizPassed: true, duration: '৪০ মিনিট' },
      { id: 2, title: 'সালাত — নামাজের গভীরতা',         isCompleted: true, isLocked: false, quizPassed: true, duration: '৬৫ মিনিট' },
      { id: 3, title: 'যাকাত ও সদকার বিধান',           isCompleted: true, isLocked: false, quizPassed: true, duration: '৫০ মিনিট' },
      { id: 4, title: 'রমজান ও সিয়াম',                 isCompleted: true, isLocked: false, quizPassed: true, duration: '৫৫ মিনিট' },
      { id: 5, title: 'হজ ও উমরা পরিচিতি',             isCompleted: true, isLocked: false, quizPassed: true, duration: '৪৮ মিনিট' },
      { id: 6, title: 'চূড়ান্ত পরীক্ষা ও সার্টিফিকেট',  isCompleted: true, isLocked: false, quizPassed: true, duration: '৩০ মিনিট' },
    ],
  },
  {
    id: 3,
    title: 'সীরাতুন নবী (ﷺ) — জীবন ও আদর্শ',
    description: 'হযরত মুহাম্মদ (ﷺ)-এর জীবনী, মক্কি ও মাদানি জীবন, গাজওয়াসমূহ এবং তাঁর চরিত্র ও আদর্শ নিয়ে বিস্তারিত আলোচনা।',
    type: 'free',
    status: 'not_enrolled',
    progress: 0,
    completedModules: 0,
    totalModules: 8,
    cover: null,
    coverGradient: 'linear-gradient(135deg, #44337A 0%, #6B46C1 100%)',
    instructor: 'ড. খালিদ হাসান',
    instructorTitle: 'পিএইচডি ইসলামিক হিস্ট্রি, ঢাকা বিশ্ববিদ্যালয়',
    duration: '৬ সপ্তাহ',
    level: 'উন্নত',
    enrolledStudents: 1847,
    rating: 4.9,
    ratingCount: 428,
    tags: ['সীরাত', 'নবীজি', 'ইতিহাস'],
    language: 'বাংলা',
    certificate: true,
    lastUpdated: '২০২৬-০৪-০১',
    modules: [
      { id: 1, title: 'মক্কায় জন্ম ও শৈশব',          isCompleted: false, isLocked: false, quizPassed: false, duration: '৫৫ মিনিট' },
      { id: 2, title: 'নবুয়তের সূচনা ও প্রথম ওহী',    isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬০ মিনিট' },
      { id: 3, title: 'মক্কায় দাওয়াত ও নির্যাতন',     isCompleted: false, isLocked: true,  quizPassed: false, duration: '৫০ মিনিট' },
      { id: 4, title: 'হিজরত ও মদিনায় আগমন',          isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬৫ মিনিট' },
      { id: 5, title: 'বদর, উহুদ ও খন্দকের যুদ্ধ',    isCompleted: false, isLocked: true,  quizPassed: false, duration: '৭০ মিনিট' },
      { id: 6, title: 'মক্কা বিজয়',                   isCompleted: false, isLocked: true,  quizPassed: false, duration: '৫৫ মিনিট' },
      { id: 7, title: 'বিদায় হজ ও শেষ ভাষণ',          isCompleted: false, isLocked: true,  quizPassed: false, duration: '৪৫ মিনিট' },
      { id: 8, title: 'চূড়ান্ত পরীক্ষা ও সার্টিফিকেট', isCompleted: false, isLocked: true,  quizPassed: false, duration: '৩০ মিনিট' },
    ],
  },
  {
    id: 5,
    title: 'ইসলামি আকিদা — তাওহিদ থেকে পরকাল',
    description: 'ইসলামের মূল আকিদাসমূহ — তাওহিদ, রিসালাত, আখিরাত, তাকদির — সম্পর্কে সহজ ভাষায় গভীর জ্ঞান অর্জন করুন।',
    type: 'free',
    status: 'not_enrolled',
    progress: 0,
    completedModules: 0,
    totalModules: 6,
    cover: null,
    coverGradient: 'linear-gradient(135deg, #155E75 0%, #0E7490 100%)',
    instructor: 'মুফতি আব্দুল্লাহ মাসুম',
    instructorTitle: 'আল-আজহার বিশ্ববিদ্যালয় গ্র্যাজুয়েট',
    duration: '৪ সপ্তাহ',
    level: 'বেসিক',
    enrolledStudents: 3102,
    rating: 4.9,
    ratingCount: 687,
    tags: ['আকিদা', 'তাওহিদ', 'ঈমান'],
    language: 'বাংলা',
    certificate: true,
    lastUpdated: '২০২৬-০৫-০৫',
    modules: [
      { id: 1, title: 'তাওহিদুর রুবুবিয়্যাহ',           isCompleted: false, isLocked: false, quizPassed: false, duration: '৫০ মিনিট' },
      { id: 2, title: 'তাওহিদুল উলুহিয়্যাহ',            isCompleted: false, isLocked: true,  quizPassed: false, duration: '৫৫ মিনিট' },
      { id: 3, title: 'রিসালাত ও নবুয়ত বিশ্বাস',        isCompleted: false, isLocked: true,  quizPassed: false, duration: '৪৮ মিনিট' },
      { id: 4, title: 'জান্নাত, জাহান্নাম ও আখিরাত',    isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬০ মিনিট' },
      { id: 5, title: 'তাকদির ও ভাগ্যে বিশ্বাস',        isCompleted: false, isLocked: true,  quizPassed: false, duration: '৪৫ মিনিট' },
      { id: 6, title: 'চূড়ান্ত পরীক্ষা ও সার্টিফিকেট', isCompleted: false, isLocked: true,  quizPassed: false, duration: '৩০ মিনিট' },
    ],
  },
  {
    id: 6,
    title: 'দৈনন্দিন জীবনে ইসলামি আদব ও সুন্নত',
    description: 'ঘুম থেকে ওঠা, খাওয়া, পোশাক ও সামাজিক জীবনের প্রতিটি ক্ষেত্রে ইসলামি আদব ও সুন্নত।',
    type: 'free',
    status: 'not_enrolled',
    progress: 0,
    completedModules: 0,
    totalModules: 4,
    cover: null,
    coverGradient: 'linear-gradient(135deg, #14532D 0%, #15803D 100%)',
    instructor: 'মাওলানা মাহমুদ হাসান',
    instructorTitle: 'ইমাম ও খতিব, বায়তুল মুকাররম মসজিদ',
    duration: '২ সপ্তাহ',
    level: 'বেসিক',
    enrolledStudents: 4215,
    rating: 4.8,
    ratingCount: 893,
    tags: ['আদব', 'সুন্নত', 'দৈনন্দিন জীবন'],
    language: 'বাংলা',
    certificate: false,
    lastUpdated: '২০২৬-০৪-২২',
    modules: [
      { id: 1, title: 'সকাল ও সন্ধ্যার সুন্নত আমল',   isCompleted: false, isLocked: false, quizPassed: false, duration: '৪০ মিনিট' },
      { id: 2, title: 'খাবার ও পানীয়ের আদব',          isCompleted: false, isLocked: true,  quizPassed: false, duration: '৩৫ মিনিট' },
      { id: 3, title: 'কথাবার্তা ও সম্পর্কের আদব',    isCompleted: false, isLocked: true,  quizPassed: false, duration: '৪৫ মিনিট' },
      { id: 4, title: 'পোশাক ও পরিচ্ছন্নতার বিধান',   isCompleted: false, isLocked: true,  quizPassed: false, duration: '৩৮ মিনিট' },
    ],
  },
  {
    id: 4,
    title: 'আরবি ভাষা মাস্টারক্লাস — কুরআনিক আরবি',
    description: 'আরবি বর্ণমালা থেকে শুরু করে কুরআনের অর্থ বোঝার মতো দক্ষতা অর্জন করুন। ব্যাকরণ, ক্রিয়াপদ ও বাক্য গঠন সবকিছু এক জায়গায়।',
    type: 'paid',
    price: 799,
    originalPrice: 1200,
    status: 'locked',
    progress: 0,
    completedModules: 0,
    totalModules: 12,
    cover: null,
    coverGradient: 'linear-gradient(135deg, #78350F 0%, #D97706 100%)',
    instructor: 'আলেম আশরাফুল ইসলাম',
    instructorTitle: 'এম.এ. আরবি সাহিত্য, মদিনা ইসলামি বিশ্ববিদ্যালয়',
    duration: '৮ সপ্তাহ',
    level: 'বেসিক',
    enrolledStudents: 648,
    rating: 4.9,
    ratingCount: 142,
    tags: ['আরবি', 'কুরআনিক আরবি', 'ব্যাকরণ'],
    language: 'বাংলা',
    certificate: true,
    liveSessions: true,
    liveSessionCount: 8,
    lastUpdated: '২০২৬-০৫-১৫',
    features: ['লাইভ ক্লাস', '১-টু-১ সেশন', 'প্রিন্টেবল ওয়ার্কশিট', 'ব্যক্তিগত ফিডব্যাক'],
    modules: [
      { id: 1,  title: 'আরবি হরফ ও হরকত পরিচয়',         isCompleted: false, isLocked: false, quizPassed: false, duration: '৫৫ মিনিট' },
      { id: 2,  title: 'সংযুক্ত হরফ ও শব্দ গঠন',         isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬০ মিনিট' },
      { id: 3,  title: 'ইসম ও এর প্রকারভেদ',             isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬৫ মিনিট' },
      { id: 4,  title: 'ফিআল (ক্রিয়া) পরিচয়',           isCompleted: false, isLocked: true,  quizPassed: false, duration: '৭০ মিনিট' },
      { id: 5,  title: 'হার্ফ ও তার ব্যবহার',             isCompleted: false, isLocked: true,  quizPassed: false, duration: '৫০ মিনিট' },
      { id: 6,  title: 'কুরআনিক শব্দভান্ডার — পর্ব ১',   isCompleted: false, isLocked: true,  quizPassed: false, duration: '৭৫ মিনিট' },
      { id: 7,  title: 'কুরআনিক শব্দভান্ডার — পর্ব ২',   isCompleted: false, isLocked: true,  quizPassed: false, duration: '৭৫ মিনিট' },
      { id: 8,  title: 'সহজ আয়াতের অর্থ বিশ্লেষণ',      isCompleted: false, isLocked: true,  quizPassed: false, duration: '৮০ মিনিট' },
      { id: 9,  title: 'বাক্য গঠন ও অনুবাদ অনুশীলন',    isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬৫ মিনিট' },
      { id: 10, title: 'সূরা থেকে সরাসরি পাঠ',            isCompleted: false, isLocked: true,  quizPassed: false, duration: '৭০ মিনিট' },
      { id: 11, title: 'লাইভ প্র্যাকটিস সেশন',            isCompleted: false, isLocked: true,  quizPassed: false, duration: '৯০ মিনিট' },
      { id: 12, title: 'চূড়ান্ত পরীক্ষা ও সার্টিফিকেট', isCompleted: false, isLocked: true,  quizPassed: false, duration: '৪৫ মিনিট' },
    ],
  },
  {
    id: 8,
    title: 'কুরআন হিফজ প্রোগ্রাম — জুজ আম্মা',
    description: 'পেশাদার হাফেজের তত্ত্বাবধানে ৩০তম পারার সূরাসমূহ মুখস্থ করুন। বৈজ্ঞানিক পদ্ধতিতে পুনরাবৃত্তি ও দৈনিক লাইভ সেশন।',
    type: 'paid',
    price: 1299,
    originalPrice: 2000,
    status: 'locked',
    progress: 0,
    completedModules: 0,
    totalModules: 10,
    cover: null,
    coverGradient: 'linear-gradient(135deg, #064E3B 0%, #10B981 100%)',
    instructor: 'হাফেজ মাওলানা জুনায়েদ আহমেদ',
    instructorTitle: 'মদিনা বিশ্ববিদ্যালয় সনদপ্রাপ্ত হাফেজ',
    duration: '১২ সপ্তাহ',
    level: 'উন্নত',
    enrolledStudents: 312,
    rating: 5.0,
    ratingCount: 87,
    tags: ['হিফজ', 'কুরআন মুখস্থ', 'জুজ আম্মা'],
    language: 'বাংলা',
    certificate: true,
    liveSessions: true,
    liveSessionCount: 24,
    lastUpdated: '২০২৬-০৬-০১',
    features: ['দৈনিক লাইভ মুরাজাআ', 'ব্যক্তিগত সংশোধন', 'রেকর্ডিং সুবিধা', 'হিফজ ট্র্যাকার'],
    modules: [
      { id: 1,  title: 'সূরা নাস থেকে সূরা তারিক',       isCompleted: false, isLocked: false, quizPassed: false, duration: '৯০ মিনিট' },
      { id: 2,  title: 'সূরা বুরুজ থেকে সূরা ইনশিকাক',  isCompleted: false, isLocked: true,  quizPassed: false, duration: '৯০ মিনিট' },
      { id: 3,  title: 'সূরা মুতাফফিফিন থেকে ইনফিতার',  isCompleted: false, isLocked: true,  quizPassed: false, duration: '৮৫ মিনিট' },
      { id: 4,  title: 'সূরা তাকউইর থেকে আবাসা',         isCompleted: false, isLocked: true,  quizPassed: false, duration: '৯০ মিনিট' },
      { id: 5,  title: 'মুরাজাআ সেশন — পর্ব ১',          isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬০ মিনিট' },
      { id: 6,  title: 'সূরা নাযিআত থেকে নাবা',          isCompleted: false, isLocked: true,  quizPassed: false, duration: '৯০ মিনিট' },
      { id: 7,  title: 'সূরা মুরসালাত থেকে জিন',         isCompleted: false, isLocked: true,  quizPassed: false, duration: '৮৫ মিনিট' },
      { id: 8,  title: 'মুরাজাআ সেশন — পর্ব ২',          isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬০ মিনিট' },
      { id: 9,  title: 'সম্পূর্ণ জুজ আম্মার পুনরাবৃত্তি', isCompleted: false, isLocked: true,  quizPassed: false, duration: '১২০ মিনিট' },
      { id: 10, title: 'চূড়ান্ত পরীক্ষা ও সার্টিফিকেট',  isCompleted: false, isLocked: true,  quizPassed: false, duration: '৯০ মিনিট' },
    ],
  },
  {
    id: 9,
    title: 'ইসলামি আর্থিক পরিকল্পনা ও হালাল বিনিয়োগ',
    description: 'হালাল উপায়ে আয়, সুদমুক্ত ব্যাংকিং, ইসলামিক শেয়ার বিনিয়োগ, যাকাত হিসাব এবং ব্যক্তিগত আর্থিক পরিকল্পনার সম্পূর্ণ গাইড।',
    type: 'paid',
    price: 999,
    originalPrice: 1500,
    status: 'locked',
    progress: 0,
    completedModules: 0,
    totalModules: 8,
    cover: null,
    coverGradient: 'linear-gradient(135deg, #312E81 0%, #4F46E5 100%)',
    instructor: 'ড. নাজমুল হক সিদ্দিকী',
    instructorTitle: 'পিএইচডি ইসলামিক ইকোনমিক্স, ইসলামিক ব্যাংক পরামর্শদাতা',
    duration: '৬ সপ্তাহ',
    level: 'মাঝারি',
    enrolledStudents: 524,
    rating: 4.8,
    ratingCount: 118,
    tags: ['হালাল ফাইন্যান্স', 'যাকাত', 'বিনিয়োগ'],
    language: 'বাংলা',
    certificate: true,
    liveSessions: true,
    liveSessionCount: 6,
    lastUpdated: '২০২৬-০৩-২৮',
    features: ['কেস স্টাডি', 'এক্সেল টেমপ্লেট', 'লাইভ Q&A সেশন', 'সার্টিফিকেট'],
    modules: [
      { id: 1, title: 'ইসলামে সম্পদ উপার্জনের বিধান',      isCompleted: false, isLocked: false, quizPassed: false, duration: '৬০ মিনিট' },
      { id: 2, title: 'রিবা (সুদ) ও তার বিকল্প',          isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬৫ মিনিট' },
      { id: 3, title: 'ইসলামিক ব্যাংকিং ও মুরাবাহা',      isCompleted: false, isLocked: true,  quizPassed: false, duration: '৭০ মিনিট' },
      { id: 4, title: 'হালাল শেয়ার ও মিউচুয়াল ফান্ড',    isCompleted: false, isLocked: true,  quizPassed: false, duration: '৭৫ মিনিট' },
      { id: 5, title: 'যাকাত ক্যালকুলেশন সম্পূর্ণ গাইড',  isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬০ মিনিট' },
      { id: 6, title: 'ওয়াকফ ও সদকাহ জারিয়ার পরিকল্পনা', isCompleted: false, isLocked: true,  quizPassed: false, duration: '৫৫ মিনিট' },
      { id: 7, title: 'ব্যক্তিগত হালাল বাজেট প্ল্যান',    isCompleted: false, isLocked: true,  quizPassed: false, duration: '৬৫ মিনিট' },
      { id: 8, title: 'চূড়ান্ত পরীক্ষা ও সার্টিফিকেট',   isCompleted: false, isLocked: true,  quizPassed: false, duration: '৩৫ মিনিট' },
    ],
  },
];

export const mockMadrasaPrograms = [
  {
    id: 1,
    title: 'প্রাথমিক দরস — নূরানী কায়দা',
    level: 'প্রাথমিক',
    duration: '৩ মাস',
    status: 'enrolled',
    progress: 45,
    modules: 6,
    completedModules: 2,
  },
  {
    id: 2,
    title: 'মাধ্যমিক দরস — কুরআনুল কারিম',
    level: 'মাধ্যমিক',
    duration: '৬ মাস',
    status: 'locked',
    progress: 0,
    modules: 12,
    completedModules: 0,
  },
];

export const mockAchievements = [
  { id: 1, title: 'প্রথম কোর্স সম্পন্ন',      icon: '🎓', unlocked: true  },
  { id: 2, title: '৭ দিনের ধারাবাহিকতা',       icon: '🔥', unlocked: true  },
  { id: 3, title: 'কুরআন পাঠক',               icon: '📖', unlocked: true  },
  { id: 4, title: '৫টি কোর্স সম্পন্ন',          icon: '⭐', unlocked: false },
  { id: 5, title: 'কুইজ চ্যাম্পিয়ন',           icon: '🏆', unlocked: false },
  { id: 6, title: 'দান-সদকাকারী',              icon: '💝', unlocked: false },
];

export const mockGallery = [
  { id: 1, title: 'বার্ষিক সম্মেলন ২০২৪', date: '২০২৪-১২-১৫', type: 'event', image: '/images/gallery_mosque_project_1782147841193.png' },
  { id: 2, title: 'কুরআন তিলাওয়াত প্রতিযোগিতা', date: '২০২৪-১১-০৫', type: 'event', image: '/images/gallery_quran_competition_1782147853584.png' },
  { id: 3, title: 'ইফতার মাহফিল ২০২৪', date: '২০২৪-০৩-২৫', type: 'event', image: '/images/gallery_iftar_1782147866691.png' },
  { id: 4, title: 'এতিম শিক্ষা কার্যক্রম', date: '২০২৪-০৮-১০', type: 'class', image: '/images/gallery_orphan_school_1782147887481.png' },
  { id: 5, title: 'অনলাইন ক্লাস সেশন', date: '২০২৪-১০-২০', type: 'class', image: '/images/gallery_online_class_1782147899608.png' },
  { id: 6, title: 'বিশুদ্ধ পানি প্রকল্প', date: '২০২৪-০৬-০৫', type: 'project', image: '/images/gallery_well_project_1782147913086.png' },
];

export const mockProjects = [
  {
    id: 1,
    title: 'মসজিদ নির্মাণ প্রকল্প',
    description: 'সুবিধাবঞ্চিত গ্রামাঞ্চলে মসজিদ নির্মাণে সহায়তা করুন। নামাজ আদায়ের সুযোগ থেকে বঞ্চিত মানুষদের কাছে আল্লাহর ঘর পৌঁছে দিন।',
    progress: 75,
    target: 500000,
    raised: 375000,
    icon: '🕌',
    category: 'অবকাঠামো',
    location: 'সিলেট, বাংলাদেশ',
    donors: 284,
    deadline: '২০২৬-০৯-৩০',
    image: '/images/gallery_mosque_project_1782147841193.png',
    status: 'চলমান',
  },
  {
    id: 2,
    title: 'এতিম শিক্ষা বৃত্তি প্রোগ্রাম',
    description: 'এতিম ও সুবিধাবঞ্চিত শিশুদের ইসলামি ও সাধারণ শিক্ষা নিশ্চিত করতে বার্ষিক বৃত্তি প্রদান করুন।',
    progress: 40,
    target: 200000,
    raised: 80000,
    icon: '📚',
    category: 'শিক্ষা',
    location: 'ঢাকা ও চট্টগ্রাম',
    donors: 156,
    deadline: '২০২৬-১২-৩১',
    image: '/images/gallery_orphan_school_1782147887481.png',
    status: 'চলমান',
  },
  {
    id: 3,
    title: 'বিশুদ্ধ পানি সরবরাহ প্রকল্প',
    description: 'দুর্গম অঞ্চলে নলকূপ স্থাপনের মাধ্যমে বিশুদ্ধ পানির ব্যবস্থা করুন। সদকায়ে জারিয়ার এই সুযোগে অংশ নিন।',
    progress: 90,
    target: 150000,
    raised: 135000,
    icon: '💧',
    category: 'মানবিক সেবা',
    location: 'রাজশাহী, বাংলাদেশ',
    donors: 421,
    deadline: '২০২৬-০৭-১৫',
    image: '/images/gallery_well_project_1782147913086.png',
    status: 'প্রায় সম্পন্ন',
  },
  {
    id: 4,
    title: 'দাওয়াহ কিট বিতরণ',
    description: 'অমুসলিম ও নওমুসলিমদের মাঝে কুরআন, ইসলামি বই ও দাওয়াহ সামগ্রী বিতরণ করুন।',
    progress: 55,
    target: 100000,
    raised: 55000,
    icon: '📖',
    category: 'দাওয়াহ',
    location: 'সারাদেশ',
    donors: 198,
    deadline: '২০২৬-১০-০১',
    image: '/images/gallery_quran_competition_1782147853584.png',
    status: 'চলমান',
  },
];

// Admin mock data
export const mockAdminStats = {
  totalUsers: 1247,
  pendingApprovals: 23,
  newDonations: 8,
  totalContent: 45,
  totalCourses: 12,
  totalDonations: 385000,
};

export const mockPendingUsers = [
  { id: 'REG-001', name: 'মোহাম্মদ আলী', email: 'ali@example.com', mobile: '01811111111', institution: 'ঢাকা কলেজ', submittedAt: '২০২৫-০১-১০', status: 'pending' },
  { id: 'REG-002', name: 'ফাতিমা বেগম', email: 'fatima@example.com', mobile: '01922222222', institution: 'ইডেন কলেজ', submittedAt: '২০২৫-০১-১০', status: 'pending' },
  { id: 'REG-003', name: 'রহিম উদ্দিন', email: 'rahim@example.com', mobile: '01533333333', institution: 'বুয়েট', submittedAt: '২০২৫-০১-০৯', status: 'pending' },
];

export const mockAllUsers = [
  { id: 'USR-001', name: 'আব্দুর রহমান', email: 'rahman@example.com', mobile: '01712345678', status: 'active', joinedDate: '২০২৫-০১-০১', coursesEnrolled: 5 },
  { id: 'USR-002', name: 'মোহাম্মদ আলী', email: 'ali@example.com', mobile: '01811111111', status: 'active', joinedDate: '২০২৫-০১-০৫', coursesEnrolled: 2 },
  { id: 'USR-003', name: 'সারা খানম', email: 'sara@example.com', mobile: '01644444444', status: 'banned', joinedDate: '২০২৪-১২-২০', coursesEnrolled: 1 },
];

export const mockDonations = [
  { id: 'DON-001', name: 'আব্দুর রহমান', mobile: '01712345678', amount: 1000, txId: 'BK2025001', method: 'bKash', status: 'verified', date: '২০২৫-০১-১০' },
  { id: 'DON-002', name: 'ফাতিমা বেগম', mobile: '01922222222', amount: 500, txId: 'NG2025002', method: 'Nagad', status: 'pending', date: '২০২৫-০১-১০' },
  { id: 'DON-003', name: 'অজ্ঞাত', mobile: '01533333333', amount: 2000, txId: 'RK2025003', method: 'Rocket', status: 'pending', date: '২০২৫-০১-০৯' },
];

export const mockFaq = [
  {
    id: 1,
    question: 'আইকিউসি অ্যাকাডেমিতে কিভাবে কোর্সে ভর্তি হবো?',
    answer: 'ওয়েবসাইটে অ্যাকাউন্ট খুলে "কোর্সসমূহ" সেকশন থেকে আপনার পছন্দের কোর্সটি নির্বাচন করুন। এরপর "ভর্তি হোন" বাটনে ক্লিক করে প্রক্রিয়াটি সম্পন্ন করুন। ফ্রি কোর্সের ক্ষেত্রে সরাসরি শুরু করতে পারবেন, আর পেইড কোর্সের ক্ষেত্রে পেমেন্ট সম্পন্ন করতে হবে।'
  },
  {
    id: 2,
    question: 'কোর্সগুলো কি লাইভ ক্লাস নাকি রেকর্ডেড?',
    answer: 'আমাদের প্ল্যাটফর্মে দুই ধরণের কোর্সই রয়েছে। বেসিক কোর্সগুলো সাধারণত রেকর্ডেড ভিডিওর মাধ্যমে হয় যা আপনি যেকোনো সময় দেখতে পারবেন। তবে প্রিমিয়াম কোর্স এবং হিফজ প্রোগ্রামগুলোতে নিয়মিত লাইভ ক্লাস ও জুম সেশন থাকে।'
  },
  {
    id: 3,
    question: 'কোর্স শেষে কি সার্টিফিকেট দেওয়া হয়?',
    answer: 'হ্যাঁ, প্রতিটি কোর্স সফলভাবে সম্পন্ন করার পর এবং সব কুইজ/পরীক্ষায় পাশ করার পর আপনাকে ডিজিটাল ভেরিফাইড সার্টিফিকেট প্রদান করা হবে, যা আপনি ডাউনলোড ও শেয়ার করতে পারবেন।'
  },
  {
    id: 4,
    question: 'আমি কিভাবে সদকাহ বা প্রোজেক্টে দান করতে পারি?',
    answer: 'ওয়েবসাইটের "প্রোজেক্ট" অথবা "ডোনেট করুন" সেকশনে গিয়ে নির্দিষ্ট প্রোজেক্ট বেছে নিয়ে বিকাশ, নগদ, রকেট অথবা ব্যাংক কার্ডের মাধ্যমে নিরাপদে দান করতে পারবেন।'
  },
  {
    id: 5,
    question: 'ক্লাস বুঝতে সমস্যা হলে কার সাথে যোগাযোগ করবো?',
    answer: 'প্রতিটি কোর্সের সাথেই একটি ডেডিকেটেড ডিসকাশন ফোরাম থাকে যেখানে আপনি প্রশ্ন করতে পারবেন। এছাড়াও প্রিমিয়াম কোর্সে ইনস্ট্রাক্টরের সাথে সরাসরি যোগাযোগের সুযোগ রয়েছে।'
  }
];

export const mockTestimonials = [
  {
    id: 1,
    name: 'আব্দুর রহমান কায়েস',
    role: 'বিশ্ববিদ্যালয় শিক্ষার্থী',
    content: 'আইকিউসি অ্যাকাডেমির "কুরআন তিলাওয়াত বেসিক কোর্স" আমার জীবন পরিবর্তন করে দিয়েছে। আগে আমি ঠিকমতো তাজবিদ মেনে পড়তে পারতাম না, এখন আলহামদুলিল্লাহ অনেক ভালো পারি। ওস্তাদজির শেখানোর পদ্ধতি অসাধারণ।',
    rating: 5,
    avatarColor: 'linear-gradient(135deg, #064E3B 0%, #10B981 100%)',
    initials: 'আক'
  },
  {
    id: 2,
    name: 'ডা. সালমা আক্তার',
    role: 'চিকিৎসক',
    content: 'ডাক্তারি পেশার ব্যস্ততার মাঝেও এখানকার ফ্লেক্সিবল রুটিন আমাকে "দৈনন্দিন ইসলামি আদব" কোর্সটি সম্পন্ন করতে সাহায্য করেছে। ক্লাসগুলো এতোটাই গোছানো যে খুব সহজেই বোঝা যায়। জাযাকাল্লাহ খাইরান পুরো টিমকে।',
    rating: 5,
    avatarColor: 'linear-gradient(135deg, #92400E 0%, #F59E0B 100%)',
    initials: 'সাআ'
  },
  {
    id: 3,
    name: 'মোহাম্মদ তারেক',
    role: 'প্রবাসী কর্মী (দুবাই)',
    content: 'প্রবাসে থেকে দ্বীনি জ্ঞান অর্জনের একটি নির্ভরযোগ্য মাধ্যম খুঁজছিলাম। আইকিউসি অ্যাকাডেমি আমার সেই শূন্যস্থান পূরণ করেছে। বিশেষ করে লাইভ সেশনগুলোতে সরাসরি ওস্তাদদের সাথে কথা বলার সুযোগটি অতুলনীয়।',
    rating: 5,
    avatarColor: 'linear-gradient(135deg, #1E3A8A 0%, #3B82F6 100%)',
    initials: 'মোতা'
  }
];
